import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

/// ---------------------------------------------------------------------
/// 1. HTTP OVERRIDES (ENTERPRISE REQUIREMENT FOR CPI)
/// Bypasses the Self-Signed Certificate generated by the CPI Service.
/// ---------------------------------------------------------------------
class CpiHttpverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) {
    return super.createHttpClient(context)
      ..badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
  }
}

class CPIHttpProtocolPageLatest extends StatelessWidget {
  const CPIHttpProtocolPageLatest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CPI Terminale POS',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF0F2537),
          primary: const Color(0xFF0F2537),
          secondary: const Color(0xFFE5A93B),
          background: const Color(0xFFF4F7F9),
        ),
        cardTheme: CardThemeData(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          elevation: 2,
        ),
      ),
      home: const CpiLoginScreen(),
    );
  }
}

/// ---------------------------------------------------------------------
/// 2. CPI API SERVICE LAYER (Strict Documentation Adherence)
/// ---------------------------------------------------------------------
class CpiApiService {
  String baseUrl = 'https://localhost:5000';
  String? accessToken;

  // Hardcoded Client ID & Secret Base64 encoded as per CPI Documentation
  final String _basicAuthHeader =
      'OWExMTc5MzBiMzJmNDNjMDg0Nzc1NjM5ZmM4ZjY3Mjg6SzhSRXVaM2JueHNGcFNHUXBFeE00Q3RqQlRtR3dQV0Y=';

  Future<bool> authenticate(
    String ipAddress,
    String username,
    String password,
  ) async {
    baseUrl = 'https://$ipAddress:5000';
    final url = Uri.parse('$baseUrl/connect/token');
    try {
      final response = await http
          .post(
            url,
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/x-www-form-urlencoded',
              'Authorization': 'Basic $_basicAuthHeader',
            },
            body:
                'grant_type=password&username=${Uri.encodeComponent(username)}&password=${Uri.encodeComponent(password)}',
          )
          .timeout(const Duration(seconds: 10));

      if (response.statusCode == 200) {
        accessToken = json.decode(response.body)['access_token'];
        return true;
      }
      return false;
    } catch (e) {
      debugPrint('Auth Error: $e');
      return false;
    }
  }

  // --- SYSTEM & DIAGNOSTICS ---
  Future<Map<String, dynamic>> getSystemStatus() async {
    final res = await http.get(
      Uri.parse('$baseUrl/api/SystemStatus'),
      headers: _authHeaders(),
    );
    if (res.statusCode == 200) return json.decode(res.body);
    throw Exception('Failed to fetch system status');
  }

  Future<Map<String, dynamic>> getSystemMessages() async {
    final res = await http.get(
      Uri.parse('$baseUrl/api/SystemStatus/Messages'),
      headers: _authHeaders(),
    );
    if (res.statusCode == 200) return json.decode(res.body);
    throw Exception('Failed to fetch messages');
  }

  Future<List<dynamic>> getDevices() async {
    final res = await http.get(
      Uri.parse('$baseUrl/api/PaymentDevices'),
      headers: _authHeaders(),
    );
    if (res.statusCode == 200) return json.decode(res.body);
    return [];
  }

  Future<List<dynamic>> getExchangeRates() async {
    final res = await http.get(
      Uri.parse('$baseUrl/api/Settings/ExchangeRateSettings'),
      headers: _authHeaders(),
    );
    if (res.statusCode == 200) return json.decode(res.body);
    return [];
  }

  // --- SESSIONS (SHIFTS) ---
  Future<Map<String, dynamic>?> getCurrentSession() async {
    final res = await http.get(
      Uri.parse('$baseUrl/api/Session/Current'),
      headers: _authHeaders(),
    );
    if (res.statusCode == 200 && res.body.isNotEmpty)
      return json.decode(res.body);
    return null;
  }

  Future<bool> startNewSession() async {
    final res = await http.post(
      Uri.parse('$baseUrl/api/Session'),
      headers: _authHeaders(),
    );
    return res.statusCode == 200 || res.statusCode == 201;
  }

  // --- TRANSACTIONS ---
  Future<String> startTransaction(
    String type,
    double amount,
    String currencyCode,
  ) async {
    // Map UI-friendly names to CPI API transactionType values
    // CPI uses "Dispense" for refunds/withdrawals, not "Refund"
    final String apiTransactionType = type == 'Refund' ? 'Dispense' : type;

    final int valueInBaseUnits = (amount * 100)
        .round(); // CPI expects base unit scaling
    final res = await http.post(
      Uri.parse('$baseUrl/api/Transactions'),
      headers: _authHeaders()..addAll({'Content-Type': 'application/json'}),
      body: json.encode({
        "currencyCode": currencyCode,
        "transactionType": apiTransactionType,
        "value": valueInBaseUnits,
      }),
    );

    if (res.statusCode == 200 || res.statusCode == 201) {
      final data = json.decode(res.body);
      return data is List ? data.first['transactionId'] : data['transactionId'];
    }
    throw Exception('Transaction Error: ${res.statusCode} - ${res.body}');
  }

  Future<Map<String, dynamic>> getTransactionDetails(String id) async {
    final res = await http.get(
      Uri.parse('$baseUrl/api/Transactions/$id'),
      headers: _authHeaders(),
    );
    if (res.statusCode == 200) return json.decode(res.body);
    throw Exception('Failed to fetch transaction');
  }

  Future<void> cancelTransaction(String id) async {
    await http.get(
      Uri.parse('$baseUrl/api/Transactions/action/$id/cancel'),
      headers: _authHeaders(),
    );
  }

  Future<void> endTransaction(String id) async {
    // Ends transaction but keeps inserted cash (Used for split payments or halting deposits)
    await http.get(
      Uri.parse('$baseUrl/api/Transactions/action/$id/end'),
      headers: _authHeaders(),
    );
  }

  /// Fetches dispensable denominations from all device recyclers.
  /// Returns a list of {value (in cents), qty} entries.
  Future<List<Map<String, int>>> getDispensableInventory() async {
    final devices = await getDevices();
    final Map<int, int> denomMap = {};
    for (final dev in devices) {
      final recyclers = dev['recyclers'];
      if (recyclers == null) continue;
      final content = recyclers is Map ? recyclers['content'] : recyclers;
      if (content is! List) continue;
      for (final recycler in content) {
        final contents = recycler['contents'];
        if (contents is! List) continue;
        for (final denom in contents) {
          final value = denom['value'] as int? ?? 0;
          final qty = denom['qty'] as int? ?? 0;
          if (value > 0 && qty > 0) {
            denomMap[value] = (denomMap[value] ?? 0) + qty;
          }
        }
      }
    }
    return denomMap.entries
        .map((e) => {'value': e.key, 'qty': e.value})
        .toList()
      ..sort((a, b) => b['value']!.compareTo(a['value']!));
  }

  Map<String, String> _authHeaders() => {
    'Authorization': 'Bearer $accessToken',
  };
}

/// Calculates whether a target amount (in cents) can be dispensed using
/// available denominations, and returns the breakdown if possible.
class DenominationCalculator {
  /// Returns a map of {denomination_value_cents: count} if the amount can
  /// be made from the available denominations, or null if impossible.
  static Map<int, int>? calculateBreakdown(
    int targetCents,
    List<Map<String, int>> inventory,
  ) {
    if (targetCents <= 0) return null;
    // Sort denominations largest-first for greedy + backtracking
    final sorted = List<Map<String, int>>.from(inventory)
      ..sort((a, b) => b['value']!.compareTo(a['value']!));

    final result = <int, int>{};
    final found = _backtrack(targetCents, sorted, 0, result);
    return found ? result : null;
  }

  static bool _backtrack(
    int remaining,
    List<Map<String, int>> denoms,
    int startIndex,
    Map<int, int> result,
  ) {
    if (remaining == 0) return true;
    if (remaining < 0 || startIndex >= denoms.length) return false;

    for (int i = startIndex; i < denoms.length; i++) {
      final denomValue = denoms[i]['value']!;
      final denomQty = denoms[i]['qty']!;
      if (denomValue > remaining || denomQty <= 0) continue;

      // Try using as many of this denomination as possible, then fewer
      final maxUsable = remaining ~/ denomValue;
      final useCount = maxUsable > denomQty ? denomQty : maxUsable;

      for (int count = useCount; count >= 1; count--) {
        result[denomValue] = count;
        // Reduce available qty for deeper recursion
        final reducedDenoms = denoms.map((d) {
          if (d['value'] == denomValue) {
            return {'value': d['value']!, 'qty': d['qty']! - count};
          }
          return Map<String, int>.from(d);
        }).toList();

        if (_backtrack(
          remaining - (denomValue * count),
          reducedDenoms,
          i + 1,
          result,
        )) {
          return true;
        }
        result.remove(denomValue);
      }
    }
    return false;
  }

  /// Converts a breakdown map into a human-readable string.
  static String formatBreakdown(Map<int, int> breakdown) {
    final parts = breakdown.entries
        .where((e) => e.value > 0)
        .map((e) => '${e.value}x ${(e.key / 100).toStringAsFixed(2)}')
        .toList();
    return parts.join(' + ');
  }
}

final cpiApi = CpiApiService();

/// ---------------------------------------------------------------------
/// 3. LOGIN SCREEN (Optimized for Landscape)
/// ---------------------------------------------------------------------
class CpiLoginScreen extends StatefulWidget {
  const CpiLoginScreen({Key? key}) : super(key: key);
  @override
  State<CpiLoginScreen> createState() => _CpiLoginScreenState();
}

class _CpiLoginScreenState extends State<CpiLoginScreen> {
  final _ipController   = TextEditingController(text: 'localhost');
  final _userController = TextEditingController(text: 'admin@cpi.com');
  final _passController = TextEditingController(text: 'Test0001');
  bool _isLoading = false;

  Future<void> _login() async {
    setState(() => _isLoading = true);
    final success = await cpiApi.authenticate(
      _ipController.text.trim(),
      _userController.text.trim(),
      _passController.text.trim(),
    );
    setState(() => _isLoading = false);

    if (success && mounted) {
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (_) => const LaptopDashboardScreen()),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
            'Connessione fallita. Controlla IP, Nome utente e Password.',
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: [
          Expanded(
            flex: 5,
            child: Container(
              color: Theme.of(context).colorScheme.primary,
              child: const Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.point_of_sale, size: 120, color: Colors.white),
                    SizedBox(height: 24),
                    Text(
                      'CPI Servizio Pagamenti POS',
                      style: TextStyle(
                        fontSize: 36,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                    SizedBox(height: 16),
                    Text(
                      'Edizione Enterprise v4.0',
                      style: TextStyle(fontSize: 18, color: Colors.white70),
                    ),
                  ],
                ),
              ),
            ),
          ),
          Expanded(
            flex: 4,
            child: Center(
              child: Container(
                constraints: const BoxConstraints(maxWidth: 450),
                padding: const EdgeInsets.all(48),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    const Text(
                      'Accedi',
                      style: TextStyle(
                        fontSize: 32,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 32),
                    TextField(
                      controller: _ipController,
                      decoration: const InputDecoration(
                        labelText: 'Indirizzo IP / Host',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.dns),
                      ),
                    ),
                    const SizedBox(height: 24),
                    TextField(
                      controller: _userController,
                      decoration: const InputDecoration(
                        labelText: 'Nome utente',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.person),
                      ),
                    ),
                    const SizedBox(height: 24),
                    TextField(
                      controller: _passController,
                      obscureText: true,
                      decoration: const InputDecoration(
                        labelText: 'Password',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.lock),
                      ),
                    ),
                    const SizedBox(height: 40),
                    SizedBox(
                      height: 60,
                      child: FilledButton(
                        onPressed: _isLoading ? null : _login,
                        child: _isLoading
                            ? const CircularProgressIndicator(
                                color: Colors.white,
                              )
                            : const Text(
                                'CONNETTI',
                                style: TextStyle(
                                  fontSize: 18,
                                  letterSpacing: 2,
                                ),
                              ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// ---------------------------------------------------------------------
/// 4. MAIN LAPTOP DASHBOARD (Sidebar + Main Content)
/// ---------------------------------------------------------------------
class LaptopDashboardScreen extends StatefulWidget {
  const LaptopDashboardScreen({Key? key}) : super(key: key);
  @override
  State<LaptopDashboardScreen> createState() => _LaptopDashboardScreenState();
}

class _LaptopDashboardScreenState extends State<LaptopDashboardScreen> {
  int _selectedIndex = 0;
  String _systemStatus = 'Checking...';
  String _sessionName = 'Loading Shift...';
  Timer? _pollingTimer;

  @override
  void initState() {
    super.initState();
    _fetchGlobalData();
    _pollingTimer = Timer.periodic(
      const Duration(seconds: 10),
      (_) => _fetchGlobalData(),
    );
  }

  @override
  void dispose() {
    _pollingTimer?.cancel();
    super.dispose();
  }

  Future<void> _fetchGlobalData() async {
    try {
      final status = await cpiApi.getSystemStatus();
      final session = await cpiApi.getCurrentSession();
      if (mounted) {
        setState(() {
          _systemStatus = status['currentStatus'] ?? 'Unknown';
          _sessionName = session != null
              ? session['sessionName']
              : 'No Active Shift';
        });
      }
    } catch (e) {
      // Background poll fail
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'CPI Terminale',
          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white),
        ),
        backgroundColor: Theme.of(context).colorScheme.primary,
        iconTheme: const IconThemeData(color: Colors.white),
        actions: [
          Chip(
            avatar: const Icon(Icons.work_history, size: 16),
            label: Text(_sessionName),
            backgroundColor: Colors.white,
          ),
          const SizedBox(width: 16),
          Chip(
            avatar: Icon(
              Icons.circle,
              size: 12,
              color: _systemStatus == 'IDLE' ? Colors.green : Colors.red,
            ),
            label: Text('Hardware: $_systemStatus'),
            backgroundColor: Colors.white,
          ),
          const SizedBox(width: 24),
        ],
      ),
      body: Row(
        children: [
          NavigationRail(
            selectedIndex: _selectedIndex,
            onDestinationSelected: (int index) =>
                setState(() => _selectedIndex = index),
            minExtendedWidth: 200,
            extended: true,
            backgroundColor: Colors.white,
            destinations: const [
              NavigationRailDestination(
                icon: Icon(Icons.point_of_sale_outlined),
                selectedIcon: Icon(Icons.point_of_sale),
                label: Text('Cassa'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.account_balance_wallet_outlined),
                selectedIcon: Icon(Icons.account_balance_wallet),
                label: Text('Gestione Cassa'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.devices_outlined),
                selectedIcon: Icon(Icons.devices),
                label: Text('Dispositivi'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.monitor_heart_outlined),
                selectedIcon: Icon(Icons.monitor_heart),
                label: Text('Diagnostica'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.work_outline),
                selectedIcon: Icon(Icons.work),
                label: Text('Turni'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.currency_exchange_outlined),
                selectedIcon: Icon(Icons.currency_exchange),
                label: Text('Tassi'),
              ),
            ],
          ),
          const VerticalDivider(thickness: 1, width: 1),
          Expanded(
            child: Container(
              color: Theme.of(context).colorScheme.background,
              child: _buildBody(),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBody() {
    switch (_selectedIndex) {
      case 0:
        return const RegisterTab();
      case 1:
        return const CashManagementTab();
      case 2:
        return const DevicesTab();
      case 3:
        return const DiagnosticsTab();
      case 4:
        return const SessionsTab();
      case 5:
        return const ExchangeRatesTab();
      default:
        return const RegisterTab();
    }
  }
}

/// ---------------------------------------------------------------------
/// TAB 1: LAPTOP OPTIMIZED REGISTER (Cart Left + Numpad Right)
/// ---------------------------------------------------------------------
class RegisterTab extends StatefulWidget {
  const RegisterTab({Key? key}) : super(key: key);
  @override
  State<RegisterTab> createState() => _RegisterTabState();
}

class _RegisterTabState extends State<RegisterTab> {
  String _amountStr = '0.00';
  String _selectedCurrency = 'EUR';

  void _onNumpadTap(String val) {
    setState(() {
      if (val == 'C') {
        _amountStr = '0.00';
      } else {
        String cleanStr = _amountStr.replaceAll('.', '');
        cleanStr += val;
        int numericVal = int.parse(cleanStr);
        _amountStr = (numericVal / 100).toStringAsFixed(2);
      }
    });
  }

  void _startTransaction(String type) {
    final amount = double.tryParse(_amountStr) ?? 0.0;
    if (type != 'Accept' && amount <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Inserisci un importo maggiore di 0.')),
      );
      return;
    }
    showDialog(
      context: context,
      barrierDismissible: true,
      builder: (_) => CpiTransactionModal(
        transactionType: type,
        amount: amount,
        currencyCode: _selectedCurrency,
      ),
    ).then((_) => setState(() => _amountStr = '0.00'));
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(24.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Left: Order Summary & Cart
          Expanded(
            flex: 5,
            child: Card(
              child: Padding(
                padding: const EdgeInsets.all(32.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Ordine Corrente',
                      style: TextStyle(
                        fontSize: 28,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const Divider(height: 32),
                    Expanded(
                      child: Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Text(
                              'Importo Dovuto',
                              style: TextStyle(
                                fontSize: 24,
                                color: Colors.grey,
                              ),
                            ),
                            const SizedBox(height: 16),
                            Text(
                              '$_selectedCurrency $_amountStr',
                              style: TextStyle(
                                fontSize: 72,
                                fontWeight: FontWeight.bold,
                                color: Theme.of(context).colorScheme.primary,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const Divider(height: 32),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text(
                          'Valuta:',
                          style: TextStyle(fontSize: 18, color: Colors.grey),
                        ),
                        DropdownButton<String>(
                          value: _selectedCurrency,
                          style: const TextStyle(
                            fontSize: 24,
                            color: Colors.black87,
                            fontWeight: FontWeight.bold,
                          ),
                          underline: const SizedBox(),
                          items: ['EUR', 'USD', 'GBP', 'CAD', 'JPY']
                              .map(
                                (c) =>
                                    DropdownMenuItem(value: c, child: Text(c)),
                              )
                              .toList(),
                          onChanged: (v) =>
                              setState(() => _selectedCurrency = v!),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
          const SizedBox(width: 24),
          // Right: Action Area & Numpad
          Expanded(
            flex: 4,
            child: Column(
              children: [
                Expanded(
                  child: GridView.count(
                    crossAxisCount: 3,
                    childAspectRatio: 1.4,
                    mainAxisSpacing: 16,
                    crossAxisSpacing: 16,
                    children: [
                      for (var i in [
                        '7',
                        '8',
                        '9',
                        '4',
                        '5',
                        '6',
                        '1',
                        '2',
                        '3',
                        'C',
                        '0',
                        '00',
                      ])
                        FilledButton.tonal(
                          style: FilledButton.styleFrom(
                            backgroundColor: i == 'C'
                                ? Colors.red.shade100
                                : Colors.white,
                            foregroundColor: i == 'C'
                                ? Colors.red.shade900
                                : Colors.black87,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                          ),
                          onPressed: () => _onNumpadTap(i == '00' ? '0' : i),
                          child: Text(
                            i,
                            style: const TextStyle(
                              fontSize: 32,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
                Row(
                  children: [
                    Expanded(
                      child: SizedBox(
                        height: 80,
                        child: FilledButton.icon(
                          style: FilledButton.styleFrom(
                            backgroundColor: Colors.green.shade700,
                          ),
                          onPressed: () => _startTransaction('Payment'),
                          icon: const Icon(Icons.payments, size: 28),
                          label: const Text(
                            'PAGA',
                            style: TextStyle(
                              fontSize: 24,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: SizedBox(
                        height: 80,
                        child: FilledButton.icon(
                          style: FilledButton.styleFrom(
                            backgroundColor: Colors.orange.shade700,
                          ),
                          onPressed: () => _startTransaction('Refund'),
                          icon: const Icon(Icons.outbox, size: 28),
                          label: const Text(
                            'RIMBORSO',
                            style: TextStyle(
                              fontSize: 24,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
                SizedBox(
                  width: double.infinity,
                  height: 60,
                  child: FilledButton.tonalIcon(
                    onPressed: () => _startTransaction('Accept'),
                    icon: const Icon(Icons.all_inbox),
                    label: const Text(
                      'DEPOSITO CONTINUO (ACCETTAZIONE)',
                      style: TextStyle(fontSize: 18),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// ---------------------------------------------------------------------
/// TAB 2: CASH MANAGEMENT (Floating, Emptying, Dispensing)
/// ---------------------------------------------------------------------
class CashManagementTab extends StatelessWidget {
  const CashManagementTab({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final ops = [
      {
        'title': 'Float verso Cassaforte',
        'type': 'FloatToCashBox',
        'icon': Icons.move_to_inbox,
        'desc': 'Sposta i fondi in eccesso oltre il float nella cassaforte.',
      },
      {
        'title': 'Float verso Erogazione',
        'type': 'FloatToDispense',
        'icon': Icons.output,
        'desc': 'Eroga manualmente i fondi in eccesso oltre il float.',
      },
      {
        'title': 'Svuota verso Cassaforte',
        'type': 'EmptyToCashBox',
        'icon': Icons.delete_sweep,
        'desc': 'Sposta tutti i fondi riciclabili nella cassaforte.',
      },
      {
        'title': 'Svuota verso Erogazione',
        'type': 'EmptyToDispense',
        'icon': Icons.eject,
        'desc': 'Eroga tutti gli elementi nei riciclatori.',
      },
    ];

    return Padding(
      padding: const EdgeInsets.all(32),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Gestione Inventario',
            style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold),
          ),
          const Text(
            'Operazioni hardware con soglie float CPI configurate.',
            style: TextStyle(fontSize: 16, color: Colors.grey),
          ),
          const SizedBox(height: 32),
          Expanded(
            child: GridView.builder(
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
                crossAxisSpacing: 24,
                mainAxisSpacing: 24,
                childAspectRatio: 2.5,
              ),
              itemCount: ops.length,
              itemBuilder: (c, i) {
                return Card(
                  child: InkWell(
                    borderRadius: BorderRadius.circular(16),
                    onTap: () {
                      showDialog(
                        context: context,
                        barrierDismissible: true,
                        builder: (_) => CpiTransactionModal(
                          transactionType: ops[i]['type'] as String,
                          amount: 0,
                          currencyCode: 'EUR',
                        ),
                      );
                    },
                    child: Padding(
                      padding: const EdgeInsets.all(24.0),
                      child: Row(
                        children: [
                          Icon(
                            ops[i]['icon'] as IconData,
                            size: 56,
                            color: Theme.of(context).colorScheme.secondary,
                          ),
                          const SizedBox(width: 24),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Text(
                                  ops[i]['title'] as String,
                                  style: const TextStyle(
                                    fontSize: 22,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                const SizedBox(height: 8),
                                Text(
                                  ops[i]['desc'] as String,
                                  style: const TextStyle(
                                    fontSize: 14,
                                    color: Colors.grey,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}

/// ---------------------------------------------------------------------
/// TAB 3: DEVICES — Connected Hardware & Info
/// ---------------------------------------------------------------------
class DevicesTab extends StatefulWidget {
  const DevicesTab({Key? key}) : super(key: key);
  @override
  State<DevicesTab> createState() => _DevicesTabState();
}

class _DevicesTabState extends State<DevicesTab> {
  List<dynamic> _devices = [];
  bool _isLoading = false;
  int? _selectedIndex;

  @override
  void initState() {
    super.initState();
    _fetchDevices();
  }

  Future<void> _fetchDevices() async {
    setState(() => _isLoading = true);
    try {
      final devices = await cpiApi.getDevices();
      setState(() {
        _devices = devices;
        _isLoading = false;
      });
    } catch (e) {
      setState(() => _isLoading = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Errore caricamento dispositivi: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  IconData _deviceIcon(String? deviceName) {
    final name = (deviceName ?? '').toUpperCase();
    if (name.contains('BNR') || name.contains('BNF')) return Icons.money;
    if (name.contains('CCR') || name.contains('CR6000'))
      return Icons.rotate_right;
    if (name.contains('CLS')) return Icons.savings;
    if (name.contains('SCN')) return Icons.document_scanner;
    if (name.contains('SCR')) return Icons.swap_horiz;
    if (name.contains('BCR')) return Icons.toll;
    return Icons.memory;
  }

  Color _stateColor(String? state) {
    switch ((state ?? '').toLowerCase()) {
      case 'idle':
        return Colors.green;
      case 'busy':
        return Colors.blue;
      case 'error':
        return Colors.red;
      case 'initializing':
        return Colors.orange;
      case 'disconnected':
        return Colors.grey;
      case 'disabled':
        return Colors.grey.shade600;
      default:
        return Colors.grey;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Dispositivi Collegati',
                style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold),
              ),
              Row(
                children: [
                  Chip(
                    avatar: const Icon(Icons.devices, size: 16),
                    label: Text('${_devices.length} dispositivo/i'),
                    backgroundColor: Colors.white,
                  ),
                  const SizedBox(width: 12),
                  _isLoading
                      ? const SizedBox(
                          width: 24,
                          height: 24,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : IconButton(
                          onPressed: _fetchDevices,
                          icon: const Icon(Icons.refresh),
                          tooltip: 'Aggiorna',
                        ),
                ],
              ),
            ],
          ),
          const SizedBox(height: 8),
          const Text(
            'Visualizza le informazioni dettagliate di ogni dispositivo hardware collegato.',
            style: TextStyle(fontSize: 14, color: Colors.grey),
          ),
          const Divider(height: 24),
          Expanded(
            child: _devices.isEmpty
                ? Center(
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(
                          Icons.devices_other,
                          size: 64,
                          color: Colors.grey.shade400,
                        ),
                        const SizedBox(height: 16),
                        Text(
                          _isLoading
                              ? 'Caricamento dispositivi...'
                              : 'Nessun dispositivo trovato',
                          style: TextStyle(
                            fontSize: 18,
                            color: Colors.grey.shade600,
                          ),
                        ),
                        if (!_isLoading) ...[
                          const SizedBox(height: 16),
                          FilledButton.icon(
                            onPressed: _fetchDevices,
                            icon: const Icon(Icons.refresh),
                            label: const Text('Riprova'),
                          ),
                        ],
                      ],
                    ),
                  )
                : Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Left: Device list
                      SizedBox(
                        width: 320,
                        child: ListView.builder(
                          itemCount: _devices.length,
                          itemBuilder: (ctx, i) {
                            final dev = _devices[i];
                            final name =
                                dev['deviceName'] ??
                                dev['name'] ??
                                'Dispositivo ${i + 1}';
                            final state =
                                dev['state'] ?? dev['status'] ?? 'Sconosciuto';
                            final isSelected = _selectedIndex == i;
                            return Card(
                              color: isSelected
                                  ? Theme.of(
                                      context,
                                    ).colorScheme.primary.withOpacity(0.1)
                                  : null,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                                side: isSelected
                                    ? BorderSide(
                                        color: Theme.of(
                                          context,
                                        ).colorScheme.primary,
                                        width: 2,
                                      )
                                    : BorderSide.none,
                              ),
                              child: ListTile(
                                leading: Container(
                                  width: 44,
                                  height: 44,
                                  decoration: BoxDecoration(
                                    color: _stateColor(state).withOpacity(0.15),
                                    borderRadius: BorderRadius.circular(10),
                                  ),
                                  child: Icon(
                                    _deviceIcon(name),
                                    color: _stateColor(state),
                                    size: 24,
                                  ),
                                ),
                                title: Text(
                                  name,
                                  style: const TextStyle(
                                    fontWeight: FontWeight.bold,
                                    fontSize: 15,
                                  ),
                                ),
                                subtitle: Row(
                                  children: [
                                    Container(
                                      width: 8,
                                      height: 8,
                                      decoration: BoxDecoration(
                                        shape: BoxShape.circle,
                                        color: _stateColor(state),
                                      ),
                                    ),
                                    const SizedBox(width: 6),
                                    Text(
                                      state,
                                      style: TextStyle(
                                        color: _stateColor(state),
                                        fontSize: 13,
                                      ),
                                    ),
                                  ],
                                ),
                                onTap: () => setState(() => _selectedIndex = i),
                              ),
                            );
                          },
                        ),
                      ),
                      const SizedBox(width: 24),
                      // Right: Device detail
                      Expanded(
                        child:
                            _selectedIndex != null &&
                                _selectedIndex! < _devices.length
                            ? _buildDeviceDetail(_devices[_selectedIndex!])
                            : Center(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Icon(
                                      Icons.touch_app,
                                      size: 56,
                                      color: Colors.grey.shade400,
                                    ),
                                    const SizedBox(height: 12),
                                    Text(
                                      'Seleziona un dispositivo per i dettagli',
                                      style: TextStyle(
                                        fontSize: 16,
                                        color: Colors.grey.shade600,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                      ),
                    ],
                  ),
          ),
        ],
      ),
    );
  }

  Widget _buildDeviceDetail(Map<String, dynamic> dev) {
    final name = dev['deviceName'] ?? dev['name'] ?? 'N/D';
    final state = dev['state'] ?? dev['status'] ?? 'Sconosciuto';
    final info = dev['deviceInfo'] as Map<String, dynamic>? ?? {};
    final errorMsg = dev['errorMessage'] ?? dev['error'];
    final warningMsg = dev['warningMessage'] ?? dev['warning'];

    // Gather all info fields
    final Map<String, String> infoFields = {};
    infoFields['Nome'] = name;
    infoFields['Stato'] = state;
    if (info['serialNumber'] != null)
      infoFields['Numero Seriale'] = '${info['serialNumber']}';
    if (info['firmwareRevision'] != null)
      infoFields['Firmware'] = '${info['firmwareRevision']}';
    if (info['softwareRevision'] != null)
      infoFields['Software'] = '${info['softwareRevision']}';
    if (info['hardwareRevision'] != null)
      infoFields['Hardware Rev.'] = '${info['hardwareRevision']}';
    if (info['manufacturer'] != null)
      infoFields['Produttore'] = '${info['manufacturer']}';
    if (info['model'] != null) infoFields['Modello'] = '${info['model']}';
    if (info['type'] != null) infoFields['Tipo'] = '${info['type']}';
    if (dev['configVersion'] != null)
      infoFields['Config'] = '${dev['configVersion']}';
    if (dev['id'] != null) infoFields['ID'] = '${dev['id']}';

    // Add remaining info fields not already captured
    for (final entry in info.entries) {
      final key = entry.key;
      if (![
        'serialNumber',
        'firmwareRevision',
        'softwareRevision',
        'hardwareRevision',
        'manufacturer',
        'model',
        'type',
      ].contains(key)) {
        infoFields[key] = '${entry.value}';
      }
    }

    // Counters
    final counters = dev['counters'] as Map<String, dynamic>? ?? {};

    return SingleChildScrollView(
      child: Card(
        child: Padding(
          padding: const EdgeInsets.all(28.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                children: [
                  Container(
                    width: 56,
                    height: 56,
                    decoration: BoxDecoration(
                      color: _stateColor(state).withOpacity(0.15),
                      borderRadius: BorderRadius.circular(14),
                      border: Border.all(
                        color: _stateColor(state).withOpacity(0.4),
                      ),
                    ),
                    child: Icon(
                      _deviceIcon(name),
                      color: _stateColor(state),
                      size: 30,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        name,
                        style: const TextStyle(
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 10,
                          vertical: 3,
                        ),
                        decoration: BoxDecoration(
                          color: _stateColor(state).withOpacity(0.15),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Text(
                          state,
                          style: TextStyle(
                            color: _stateColor(state),
                            fontWeight: FontWeight.w600,
                            fontSize: 13,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),

              // Error banner
              if (errorMsg != null) ...[
                const SizedBox(height: 16),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(14),
                  decoration: BoxDecoration(
                    color: Colors.red.shade50,
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(color: Colors.red.shade300),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        Icons.error_outline,
                        color: Colors.red.shade700,
                        size: 20,
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Errore Dispositivo',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.red.shade700,
                                fontSize: 14,
                              ),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              '$errorMsg',
                              style: TextStyle(
                                color: Colors.red.shade900,
                                fontSize: 13,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ],

              // Warning banner
              if (warningMsg != null) ...[
                const SizedBox(height: 16),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(14),
                  decoration: BoxDecoration(
                    color: Colors.orange.shade50,
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(color: Colors.orange.shade300),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        Icons.warning_amber,
                        color: Colors.orange.shade700,
                        size: 20,
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Avviso Dispositivo',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.orange.shade700,
                                fontSize: 14,
                              ),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              '$warningMsg',
                              style: TextStyle(
                                color: Colors.orange.shade900,
                                fontSize: 13,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ],

              const SizedBox(height: 24),
              // Info table
              const Text(
                'Informazioni Dispositivo',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600),
              ),
              const Divider(height: 20),
              ...infoFields.entries.map(
                (e) => Padding(
                  padding: const EdgeInsets.symmetric(vertical: 5),
                  child: Row(
                    children: [
                      SizedBox(
                        width: 160,
                        child: Text(
                          e.key,
                          style: const TextStyle(
                            fontSize: 14,
                            color: Colors.grey,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Expanded(
                        child: Text(
                          e.value,
                          style: const TextStyle(fontSize: 14),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              // Counters
              if (counters.isNotEmpty) ...[
                const SizedBox(height: 24),
                const Text(
                  'Contatori',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600),
                ),
                const Divider(height: 20),
                ...counters.entries.map(
                  (e) => Padding(
                    padding: const EdgeInsets.symmetric(vertical: 5),
                    child: Row(
                      children: [
                        SizedBox(
                          width: 160,
                          child: Text(
                            e.key,
                            style: const TextStyle(
                              fontSize: 14,
                              color: Colors.grey,
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                        ),
                        Expanded(
                          child: Text(
                            '${e.value}',
                            style: const TextStyle(fontSize: 14),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],

              // Raw JSON section for any additional unstructured data
              const SizedBox(height: 24),
              ExpansionTile(
                title: const Text(
                  'Dati Grezzi (JSON)',
                  style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
                ),
                tilePadding: EdgeInsets.zero,
                childrenPadding: const EdgeInsets.only(top: 8),
                children: [
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: const Color(0xFF1E1E1E),
                      borderRadius: BorderRadius.circular(10),
                    ),
                    child: SelectableText(
                      const JsonEncoder.withIndent('  ').convert(dev),
                      style: const TextStyle(
                        color: Colors.greenAccent,
                        fontFamily: 'monospace',
                        fontSize: 12,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// ---------------------------------------------------------------------
/// TAB 4: DIAGNOSTICS & SYSTEM MESSAGES
/// ---------------------------------------------------------------------
class DiagnosticsTab extends StatefulWidget {
  const DiagnosticsTab({Key? key}) : super(key: key);
  @override
  State<DiagnosticsTab> createState() => _DiagnosticsTabState();
}

class _DiagnosticsTabState extends State<DiagnosticsTab> {
  List<dynamic> _devices = [];
  Map<String, dynamic>? _messages;

  @override
  void initState() {
    super.initState();
    _fetchDiagnostics();
  }

  Future<void> _fetchDiagnostics() async {
    try {
      final devices = await cpiApi.getDevices();
      final msgs = await cpiApi.getSystemMessages();
      setState(() {
        _devices = devices;
        _messages = msgs;
      });
    } catch (e) {
      debugPrint('Diag Error: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(32.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      'Hardware Collegato',
                      style: TextStyle(
                        fontSize: 24,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    IconButton(
                      onPressed: _fetchDiagnostics,
                      icon: const Icon(Icons.refresh),
                    ),
                  ],
                ),
                const Divider(),
                Expanded(
                  child: ListView.builder(
                    itemCount: _devices.length,
                    itemBuilder: (c, i) {
                      final dev = _devices[i];
                      final state = dev['state'] ?? 'Sconosciuto';
                      final hasError =
                          dev['errorMessage'] != null || dev['error'] != null;
                      final hasWarning =
                          dev['warningMessage'] != null ||
                          dev['warning'] != null;
                      return Card(
                        margin: const EdgeInsets.only(bottom: 12),
                        child: ExpansionTile(
                          leading: Icon(
                            Icons.memory,
                            size: 36,
                            color: hasError
                                ? Colors.red
                                : (hasWarning
                                      ? Colors.orange
                                      : (state == 'Idle'
                                            ? Colors.green
                                            : Colors.grey)),
                          ),
                          title: Text(
                            '${dev['deviceName'] ?? 'Dispositivo'} - $state',
                            style: const TextStyle(fontWeight: FontWeight.bold),
                          ),
                          subtitle: Text(
                            'SN: ${dev['deviceInfo']?['serialNumber'] ?? 'N/D'} | FW: ${dev['deviceInfo']?['firmwareRevision'] ?? 'N/D'}',
                          ),
                          children: [
                            if (hasError)
                              Container(
                                width: double.infinity,
                                margin: const EdgeInsets.symmetric(
                                  horizontal: 16,
                                  vertical: 4,
                                ),
                                padding: const EdgeInsets.all(10),
                                decoration: BoxDecoration(
                                  color: Colors.red.shade50,
                                  borderRadius: BorderRadius.circular(8),
                                  border: Border.all(
                                    color: Colors.red.shade300,
                                  ),
                                ),
                                child: Row(
                                  children: [
                                    Icon(
                                      Icons.error_outline,
                                      color: Colors.red.shade700,
                                      size: 18,
                                    ),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Text(
                                        '${dev['errorMessage'] ?? dev['error']}',
                                        style: TextStyle(
                                          color: Colors.red.shade900,
                                          fontSize: 13,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            if (hasWarning)
                              Container(
                                width: double.infinity,
                                margin: const EdgeInsets.symmetric(
                                  horizontal: 16,
                                  vertical: 4,
                                ),
                                padding: const EdgeInsets.all(10),
                                decoration: BoxDecoration(
                                  color: Colors.orange.shade50,
                                  borderRadius: BorderRadius.circular(8),
                                  border: Border.all(
                                    color: Colors.orange.shade300,
                                  ),
                                ),
                                child: Row(
                                  children: [
                                    Icon(
                                      Icons.warning_amber,
                                      color: Colors.orange.shade700,
                                      size: 18,
                                    ),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Text(
                                        '${dev['warningMessage'] ?? dev['warning']}',
                                        style: TextStyle(
                                          color: Colors.orange.shade900,
                                          fontSize: 13,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            Padding(
                              padding: const EdgeInsets.all(16),
                              child: Text(
                                const JsonEncoder.withIndent('  ').convert(dev),
                                style: const TextStyle(
                                  fontFamily: 'monospace',
                                  fontSize: 12,
                                ),
                              ),
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(width: 32),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Log di Sistema e Avvisi',
                  style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                ),
                const Divider(),
                Expanded(
                  child: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(24),
                    decoration: BoxDecoration(
                      color: const Color(0xFF1E1E1E),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: SelectableText(
                      _messages != null
                          ? const JsonEncoder.withIndent(
                              '  ',
                            ).convert(_messages)
                          : 'Caricamento o nessun messaggio...',
                      style: const TextStyle(
                        color: Colors.greenAccent,
                        fontFamily: 'monospace',
                        fontSize: 14,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// ---------------------------------------------------------------------
/// TAB 5: SHIFT / SESSION MANAGEMENT
/// ---------------------------------------------------------------------
class SessionsTab extends StatefulWidget {
  const SessionsTab({Key? key}) : super(key: key);
  @override
  State<SessionsTab> createState() => _SessionsTabState();
}

class _SessionsTabState extends State<SessionsTab> {
  Map<String, dynamic>? _currentSession;
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _loadSession();
  }

  Future<void> _loadSession() async {
    final session = await cpiApi.getCurrentSession();
    setState(() => _currentSession = session);
  }

  Future<void> _startNewShift() async {
    setState(() => _isLoading = true);
    final success = await cpiApi.startNewSession();
    await _loadSession();
    setState(() => _isLoading = false);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            success
                ? 'Turno precedente finalizzato. Nuovo turno avviato.'
                : 'Impossibile avviare il turno.',
          ),
          backgroundColor: success ? Colors.green : Colors.red,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Card(
        child: Container(
          width: 500,
          padding: const EdgeInsets.all(40),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.work_history, size: 80, color: Colors.blueGrey),
              const SizedBox(height: 24),
              const Text(
                'Gestione Turni',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 32),
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Colors.grey.shade100,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Column(
                  children: [
                    const Text(
                      'ID Sessione Corrente',
                      style: TextStyle(color: Colors.grey),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      _currentSession?['sessionName'] ?? 'Nessun Turno Attivo',
                      style: const TextStyle(
                        fontSize: 22,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),
                    const Text(
                      'Iniziato Il',
                      style: TextStyle(color: Colors.grey),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      _currentSession?['startTimestamp'] ?? 'N/D',
                      style: const TextStyle(fontSize: 16),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 40),
              SizedBox(
                width: double.infinity,
                height: 60,
                child: FilledButton.icon(
                  onPressed: _isLoading ? null : _startNewShift,
                  icon: const Icon(Icons.lock_clock),
                  label: const Text(
                    'FINALIZZA E AVVIA NUOVO TURNO',
                    style: TextStyle(fontSize: 16),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// ---------------------------------------------------------------------
/// TAB 6: EXCHANGE RATES
/// ---------------------------------------------------------------------
class ExchangeRatesTab extends StatefulWidget {
  const ExchangeRatesTab({Key? key}) : super(key: key);
  @override
  State<ExchangeRatesTab> createState() => _ExchangeRatesTabState();
}

class _ExchangeRatesTabState extends State<ExchangeRatesTab> {
  List<dynamic> _rates = [];

  @override
  void initState() {
    super.initState();
    _fetchRates();
  }

  Future<void> _fetchRates() async {
    try {
      final rates = await cpiApi.getExchangeRates();
      setState(() => _rates = rates);
    } catch (e) {
      debugPrint('Rates Error: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(32.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Tassi di Cambio Hardware',
                style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold),
              ),
              IconButton(
                onPressed: _fetchRates,
                icon: const Icon(Icons.refresh),
              ),
            ],
          ),
          const Divider(),
          const SizedBox(height: 16),
          Expanded(
            child: _rates.isEmpty
                ? const Center(
                    child: Text(
                      'Nessun tasso esterno configurato.',
                      style: TextStyle(fontSize: 18, color: Colors.grey),
                    ),
                  )
                : ListView.builder(
                    itemCount: _rates.length,
                    itemBuilder: (c, i) {
                      final rate = _rates[i];
                      return Card(
                        child: ListTile(
                          leading: const Icon(
                            Icons.currency_exchange,
                            size: 32,
                          ),
                          title: Text(
                            '${rate['fromCurrency']} ➔ ${rate['toCurrency']}',
                            style: const TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          trailing: Text(
                            'Tasso: ${rate['exchangeRate']}',
                            style: const TextStyle(fontSize: 20),
                          ),
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}

/// ---------------------------------------------------------------------
/// 5. UNIVERSAL TRANSACTION MODAL (Real-time Feedback & Polling)
/// Handles standard transactions, Accepts, and Hardware level float downs.
/// Includes support for Split Payments by halting via 'End' API.
/// ---------------------------------------------------------------------
class CpiTransactionModal extends StatefulWidget {
  final String transactionType;
  final double amount;
  final String currencyCode;

  const CpiTransactionModal({
    Key? key,
    required this.transactionType,
    required this.amount,
    required this.currencyCode,
  }) : super(key: key);

  @override
  State<CpiTransactionModal> createState() => _CpiTransactionModalState();
}

class _CpiTransactionModalState extends State<CpiTransactionModal> {
  String? _transactionId;
  String _status = 'Inizializzazione dispositivo...';
  double _totalAccepted = 0.0;
  double _totalDispensed = 0.0;
  Timer? _pollingTimer;
  bool _isFinished = false;
  String? _errorDetails;
  // Smart dispense: split into multiple sub-transactions
  bool _isSmartDispensing = false;
  int _smartDispenseTotal = 0;
  double _smartTotalDispensed = 0.0;

  @override
  void initState() {
    super.initState();
    _initiateTransaction();
  }

  bool get _isDispenseType =>
      widget.transactionType == 'Refund' ||
      widget.transactionType == 'Dispense';

  Future<void> _initiateTransaction() async {
    try {
      _transactionId = await cpiApi.startTransaction(
        widget.transactionType,
        widget.amount,
        widget.currencyCode,
      );
      setState(() => _status = 'Elaborazione hardware...');
      _startPolling();
    } catch (e) {
      // If dispense fails immediately, attempt smart denomination split
      if (_isDispenseType && !_isSmartDispensing) {
        await _attemptSmartDispense();
      } else {
        setState(() {
          _status = 'Errore Avvio';
          _errorDetails = '$e';
          _isFinished = true;
        });
      }
    }
  }

  /// When a Dispense fails with InsufficientChange, queries device inventory
  /// and attempts to split into multiple smaller dispense transactions using
  /// available denominations that sum to the requested amount.
  Future<void> _attemptSmartDispense() async {
    setState(() {
      _status = 'Verifica erogazione alternativa...';
      _errorDetails = null;
    });

    try {
      final inventory = await cpiApi.getDispensableInventory();
      final targetCents = (widget.amount * 100).round();
      final breakdown = DenominationCalculator.calculateBreakdown(
        targetCents,
        inventory,
      );

      if (breakdown == null || breakdown.isEmpty) {
        setState(() {
          _status = 'Resto Insufficiente nel Sistema!';
          _errorDetails =
              'Impossibile erogare ${widget.currencyCode} ${widget.amount.toStringAsFixed(2)} '
              'con le denominazioni disponibili.';
          _isFinished = true;
        });
        return;
      }

      // Start smart dispense sequence
      final dispenseSteps = <double>[];
      for (final entry in breakdown.entries) {
        final denomEur = entry.key / 100.0;
        for (int i = 0; i < entry.value; i++) {
          dispenseSteps.add(denomEur);
        }
      }

      setState(() {
        _isSmartDispensing = true;
        _smartDispenseTotal = dispenseSteps.length;
        _smartTotalDispensed = 0.0;
        _status =
            'Erogazione suddivisa: ${DenominationCalculator.formatBreakdown(breakdown)}';
      });

      // Execute each sub-dispense sequentially
      for (int i = 0; i < dispenseSteps.length; i++) {
        if (!mounted) return;
        final stepAmount = dispenseSteps[i];
        setState(() {
          _status =
              'Erogazione ${i + 1}/$_smartDispenseTotal: '
              '${widget.currencyCode} ${stepAmount.toStringAsFixed(2)}';
        });

        try {
          final subTxId = await cpiApi.startTransaction(
            widget.transactionType,
            stepAmount,
            widget.currencyCode,
          );
          // Wait for sub-transaction to complete
          await _waitForTransactionCompletion(subTxId);
          _smartTotalDispensed += stepAmount;
          if (mounted) {
            setState(() {
              _totalDispensed = _smartTotalDispensed;
            });
          }
        } catch (e) {
          if (mounted) {
            setState(() {
              _status = 'Errore durante erogazione suddivisa';
              _errorDetails =
                  'Erogato ${widget.currencyCode} ${_smartTotalDispensed.toStringAsFixed(2)} '
                  'di ${widget.currencyCode} ${widget.amount.toStringAsFixed(2)}. '
                  'Errore passo ${i + 1}: $e';
              _isFinished = true;
            });
          }
          return;
        }
      }

      // All sub-transactions completed
      if (mounted) {
        setState(() {
          _status = 'Transazione Completata!';
          _totalDispensed = _smartTotalDispensed;
          _isFinished = true;
        });
      }
    } catch (e) {
      setState(() {
        _status = 'Resto Insufficiente nel Sistema!';
        _errorDetails = '$e';
        _isFinished = true;
      });
    }
  }

  /// Waits for a sub-transaction to reach a terminal state by polling.
  Future<void> _waitForTransactionCompletion(String transactionId) async {
    const maxAttempts = 60; // 60 seconds max per sub-transaction
    for (int attempt = 0; attempt < maxAttempts; attempt++) {
      await Future.delayed(const Duration(seconds: 1));
      final details = await cpiApi.getTransactionDetails(transactionId);
      final apiStatus = details['status'] ?? 'Unknown';

      if (apiStatus == 'CompletedSuccess') return;

      if ([
        'Cancelled',
        'DeviceError',
        'InsufficientChange',
        'NotStartedInsufficientChange',
        'NotStartedBusy',
      ].contains(apiStatus)) {
        throw Exception('Sub-transazione fallita: $apiStatus');
      }
    }
    throw Exception('Timeout sub-transazione');
  }

  void _startPolling() {
    _pollingTimer = Timer.periodic(const Duration(seconds: 1), (timer) async {
      if (_transactionId == null) return;
      try {
        final details = await cpiApi.getTransactionDetails(_transactionId!);
        final apiStatus = details['status'] ?? 'Unknown';

        // CPI returns amounts in cents. Scale to standard double format natively
        final rawAccepted = details['totalAccepted'] ?? 0;
        final rawDispensed = details['totalDispensed'] ?? 0;

        if (mounted) {
          setState(() {
            _totalAccepted = rawAccepted / 100.0;
            _totalDispensed = rawDispensed / 100.0;
            _status = _formatApiStatus(apiStatus);
            // Capture error details from response
            if (details['errorMessage'] != null) {
              _errorDetails = '${details['errorMessage']}';
            } else if (details['error'] != null) {
              _errorDetails = '${details['error']}';
            } else if (details['warningMessage'] != null ||
                details['warning'] != null) {
              _errorDetails =
                  '${details['warningMessage'] ?? details['warning']}';
            }
          });
        }

        // Terminal device states
        if ([
          'CompletedSuccess',
          'Cancelled',
          'DeviceError',
          'NotStartedBusy',
          'NotStarted',
        ].contains(apiStatus)) {
          timer.cancel();
          setState(() => _isFinished = true);
        }

        // InsufficientChange: attempt smart denomination split before giving up
        if ([
          'InsufficientChange',
          'NotStartedInsufficientChange',
        ].contains(apiStatus)) {
          timer.cancel();
          if (_isDispenseType && !_isSmartDispensing) {
            _attemptSmartDispense();
          } else {
            setState(() => _isFinished = true);
          }
        }
      } catch (e) {
        debugPrint('Polling Error: $e');
      }
    });
  }

  String _formatApiStatus(String apiStatus) {
    switch (apiStatus) {
      case 'InProgress':
        return widget.transactionType == 'Accept'
            ? 'Accettazione deposito continuo...'
            : 'In attesa inserimento contanti...';
      case 'CompletedSuccess':
        return 'Transazione Completata!';
      case 'Cancelled':
        return 'Transazione Annullata e Depositata.';
      case 'InsufficientChange':
        return 'Resto Insufficiente nel Sistema!';
      case 'NotStartedInsufficientChange':
        return 'Bloccato: Impossibile erogare resto.';
      case 'NotStartedBusy':
        return 'Errore Hardware / Occupato: Controllare connessione.';
      case 'NotStarted':
        return 'Avvio Controller Hardware...';
      case 'DeviceError':
        return 'Inceppamento o Errore Hardware Rilevato.';
      default:
        return apiStatus;
    }
  }

  Future<void> _cancelFull() async {
    if (_transactionId != null) {
      setState(() => _status = 'Annullamento e deposito contanti...');
      await cpiApi.cancelTransaction(_transactionId!);
    }
  }

  Future<void> _splitPaymentEnd() async {
    if (_transactionId != null) {
      setState(() => _status = 'Fine fase contanti e salvataggio...');
      // Calls /action/end to keep currently inserted cash (Split payment functionality)
      await cpiApi.endTransaction(_transactionId!);
    }
  }

  @override
  void dispose() {
    _pollingTimer?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: true,
      onPopInvokedWithResult: (didPop, result) {
        if (didPop && !_isFinished && _transactionId != null) {
          _cancelFull();
        }
      },
      child: Dialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        child: Container(
          width: 700,
          padding: const EdgeInsets.all(48),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'Operazione: ${_localizeTransactionType(widget.transactionType)}',
                style: const TextStyle(
                  fontSize: 20,
                  color: Colors.grey,
                  letterSpacing: 1.2,
                ),
              ),
              const SizedBox(height: 16),
              Text(
                _status,
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 36,
                  fontWeight: FontWeight.bold,
                  color: Theme.of(context).colorScheme.primary,
                ),
              ),

              // Error/Warning details banner
              if (_errorDetails != null) ...[
                Container(
                  width: double.infinity,
                  margin: const EdgeInsets.only(top: 12, bottom: 4),
                  padding: const EdgeInsets.all(14),
                  decoration: BoxDecoration(
                    color: _isFinished
                        ? Colors.red.shade50
                        : Colors.orange.shade50,
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(
                      color: _isFinished
                          ? Colors.red.shade300
                          : Colors.orange.shade300,
                    ),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        _isFinished ? Icons.error_outline : Icons.warning_amber,
                        color: _isFinished
                            ? Colors.red.shade700
                            : Colors.orange.shade700,
                        size: 20,
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              _isFinished ? 'Dettagli Errore' : 'Avviso',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: _isFinished
                                    ? Colors.red.shade700
                                    : Colors.orange.shade700,
                                fontSize: 13,
                              ),
                            ),
                            const SizedBox(height: 4),
                            SelectableText(
                              _errorDetails!,
                              style: TextStyle(
                                color: _isFinished
                                    ? Colors.red.shade900
                                    : Colors.orange.shade900,
                                fontSize: 13,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ],

              const SizedBox(height: 24),

              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  if (widget.amount > 0) _buildStat('Dovuto', widget.amount),
                  _buildStat(
                    'Accettato',
                    _totalAccepted,
                    isHighlight: _totalAccepted > 0,
                  ),
                  _buildStat(
                    'Erogato',
                    _totalDispensed,
                    isHighlight: _totalDispensed > 0,
                  ),
                ],
              ),

              const SizedBox(height: 48),
              if (!_isFinished)
                const LinearProgressIndicator(
                  minHeight: 8,
                  borderRadius: BorderRadius.all(Radius.circular(4)),
                ),
              const SizedBox(height: 48),

              if (_isFinished)
                SizedBox(
                  width: double.infinity,
                  height: 70,
                  child: FilledButton(
                    onPressed: () => Navigator.pop(context),
                    child: const Text('CHIUDI', style: TextStyle(fontSize: 22)),
                  ),
                )
              else if (widget.transactionType == 'Accept')
                SizedBox(
                  width: double.infinity,
                  height: 70,
                  child: FilledButton(
                    style: FilledButton.styleFrom(
                      backgroundColor: Theme.of(context).colorScheme.secondary,
                    ),
                    onPressed: _splitPaymentEnd,
                    child: const Text(
                      'TERMINA ACCETTAZIONE',
                      style: TextStyle(fontSize: 22),
                    ),
                  ),
                )
              else
                Row(
                  children: [
                    Expanded(
                      child: SizedBox(
                        height: 70,
                        child: OutlinedButton(
                          style: OutlinedButton.styleFrom(
                            foregroundColor: Colors.red.shade700,
                            side: BorderSide(
                              color: Colors.red.shade700,
                              width: 2,
                            ),
                          ),
                          onPressed: _cancelFull,
                          child: const Text(
                            'ANNULLA (RESTITUISCI)',
                            style: TextStyle(fontSize: 18),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: SizedBox(
                        height: 70,
                        child: FilledButton(
                          style: FilledButton.styleFrom(
                            backgroundColor: Theme.of(
                              context,
                            ).colorScheme.secondary,
                          ),
                          // Split Payment: Ends transaction but keeps the money currently accepted
                          onPressed: _splitPaymentEnd,
                          child: const Text(
                            'PAGAMENTO DIVISO',
                            style: TextStyle(fontSize: 18),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
            ],
          ),
        ),
      ), // end Dialog
    ); // end PopScope
  }

  Widget _buildStat(String label, double value, {bool isHighlight = false}) {
    return Column(
      children: [
        Text(label, style: const TextStyle(fontSize: 20, color: Colors.grey)),
        const SizedBox(height: 12),
        Text(
          '${widget.currencyCode} ${value.toStringAsFixed(2)}',
          style: TextStyle(
            fontSize: 40,
            fontWeight: FontWeight.bold,
            color: isHighlight ? Colors.green.shade700 : Colors.black87,
          ),
        ),
      ],
    );
  }

  String _localizeTransactionType(String type) {
    switch (type) {
      case 'Payment':
        return 'Pagamento';
      case 'Refund':
        return 'Rimborso';
      case 'Accept':
        return 'Deposito Continuo';
      case 'FloatToCashBox':
        return 'Float verso Cassaforte';
      case 'FloatToDispense':
        return 'Float verso Erogazione';
      case 'EmptyToCashBox':
        return 'Svuota verso Cassaforte';
      case 'EmptyToDispense':
        return 'Svuota verso Erogazione';
      default:
        return type;
    }
  }
}
